# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-10 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('dateofbirth', models.DateField()),
                ('ticket_number', models.IntegerField()),
                ('enroled_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
