# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='captain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enroled_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Group'),
        ),
    ]
